language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install opentracing
  # TODO: Change to `pip install wavefront-sdk-python` once it's released
  - pip install git+https://github.com/wavefrontHQ/wavefront-sdk-python.git

script:
  - python -m unittest discover
