dist: xenial

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install mock
  - pip install freezegun
  - pip install opentracing
#  TODO: change back once new version of wavefront-sdk-python is released.
#  - pip install wavefront-sdk-python
  - pip install git+https://github.com/wavefrontHQ/wavefront-sdk-python.git
#  TODO: change back once new version of pyformance is released.
#  - pip install wavefront-pyformance
  - pip install git+https://github.com/wavefrontHQ/wavefront-pyformance.git

script:
  - python -m unittest discover
