dist: xenial

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install mock
  - pip install wavefront-pyformance
  - pip install opentracing
  - pip install wavefront-sdk-python

script:
  - python -m unittest discover
