language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install opentracing
  - pip install git+https://github.com/wavefrontHQ/wavefront-python-sdk.git

script:
  - python -m unittest discover
