dist: xenial

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install mock
#  TODO: change back once new version of pyformance is released.
#  - pip install wavefront-pyformance
  - pip install git+https://github.com/wavefrontHQ/wavefront-pyformance.git
  - pip install opentracing
  - pip install wavefront-sdk-python

script:
  - python -m unittest discover
